### ISSUE TITLE
Dependency ‘im’ is not available for package ‘biva’

### ISSUE THREAD

**Issue by kirangauthier** [google/biva#6]
Hi Yichi, 

In calling 

```
library(devtools)
devtools::install_github("google/BIVA")
``` 

I get this list of packages: 

```
Downloading GitHub repo google/BIVA@HEAD
Skipping 1 packages not available: im
Installing 7 packages: corrplot, rstatix, ggsignif, ggsci, vizdraws, im, ggpubr
``` 

however, I run into the below error 

```
ERROR: dependency ‘im’ is not available for package ‘biva’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/biva’
Warning messages:
1: package ‘im’ is not available for this version of R
``` 

I'm running R 4.4.1, and thought that downgrading might help, but I looked on [CRAN](https://cran.r-project.org/web/packages/available_packages_by_name.html#available-packages-I) and couldn't find the `im` package there. Could you let me know what would be the best way to resolve this issue?

**Comment by ignacio82** [comment]
It should work now:
https://github.com/google/im

**Comment by kirangauthier** [comment]
thanks Ignacio, I'll try it on my end tomorrow.
